### ISSUE TITLE
Refactor Express Logic

### ISSUE THREAD

**Issue by loljoho** [jacobwilder/git-battle#9]
## Overview

Much of the logic currently found in the `routes/` files should be put into appropriate `controllers/` files...amongst other principles of [Model–View–Controller](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) design patterns.

Additionally, using team members as function and variables is horrible for debugging.  I'd rather step on a anti-personnel mine made of LEGOs.

## Tasks

**Files**
 - [x] Create separate `data-controller.js` controller file for data logic (GitHub API calls)
 - [x] Create separate `data.js` route file for data (leaderboard)
 - [x] Create separate `user.js` route file for user (GitHub API calls)

**Code**
 - [x] Move [non-route code](https://github.com/jacobwilder/git-battle/blob/develop/routes/api/index.js#L71-L171) into controllers
 - [x] Fix `import` and `export` statements accordingly
 - [x] Rename `getManuel()` function
 - [x] Rename `manuel` variable
 - [x] Rename `kevin` variable

## Workflow

All work will be done in the branch [`feat/1-refactor-express-logic`](https://github.com/jacobwilder/git-battle/tree/feat/1-refactor-express-logic), which has been checked out from `develop`, and will be merged back into `develop` upon completion.

[See this article](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) for more information about this workflow.  (Note: I am not using any of the recommended tools).
